import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const ENV_PATH = path.join(ROOT, ".env.local");
const shouldReset = process.argv.includes("--reset");
const SUPABASE_COMMAND = "npx supabase"

function run(command, options = {}) {
	return execSync(command, {
		cwd: ROOT,
		stdio: ["ignore", "pipe", "pipe"],
		encoding: "utf8",
		...options,
	});
}

function runLogged(command) {
	process.stdout.write(`$ ${command}\n`);
	const output = run(command);
	if (output.trim()) process.stdout.write(`${output.trim()}\n`);
	return output;
}

function ensureSupabaseCli() {
	try {
		run(`${SUPABASE_COMMAND} --version`);
	} catch {
		throw new Error(
			"Supabase CLI is not installed. Install it first: https://supabase.com/docs/guides/cli/getting-started",
		);
	}
}

function parseKeyValueLines(input) {
	const values = {};
	for (const rawLine of input.split(/\r?\n/)) {
		const line = rawLine.trim();
		if (!line || line.startsWith("#")) continue;

		const separatorIndex = line.indexOf("=");
		if (separatorIndex <= 0) continue;

		const key = line.slice(0, separatorIndex).trim();
		const value = line.slice(separatorIndex + 1).trim();
		values[key] = value;
	}
	return values;
}

function getSupabaseStatusEnv() {
	try {
		const envOutput = run(`${SUPABASE_COMMAND} status -o env`);
		return parseKeyValueLines(envOutput);
	} catch {
		const jsonOutput = run(`${SUPABASE_COMMAND} status -o json`);
		const parsed = JSON.parse(jsonOutput);

		return {
			API_URL: parsed.API_URL ?? parsed.api_url ?? "",
			ANON_KEY: parsed.ANON_KEY ?? parsed.anon_key ?? "",
			SERVICE_ROLE_KEY:
				parsed.SERVICE_ROLE_KEY ?? parsed.service_role_key ?? "",
		};
	}
}

function readExistingEnvFile() {
	if (!fs.existsSync(ENV_PATH)) return {};
	return parseKeyValueLines(fs.readFileSync(ENV_PATH, "utf8"));
}

function writeEnvFile(values) {
	const lines = [
		"# Generated by scripts/supabase-local.mjs",
		`NEXT_PUBLIC_SUPABASE_URL=${values.NEXT_PUBLIC_SUPABASE_URL}`,
		`NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${values.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}`,
	];

	if (values.SUPABASE_SERVICE_ROLE_KEY) {
		lines.push(`SUPABASE_SERVICE_ROLE_KEY=${values.SUPABASE_SERVICE_ROLE_KEY}`);
	}

	fs.writeFileSync(ENV_PATH, `${lines.join("\n")}\n`, "utf8");
}

function main() {
	ensureSupabaseCli();

	runLogged(`${SUPABASE_COMMAND} start`);

	if (shouldReset) {
		runLogged(`${SUPABASE_COMMAND} db reset --local`);
	}

	const statusEnv = getSupabaseStatusEnv();
	const existingEnv = readExistingEnvFile();

	const url =
		statusEnv.API_URL ||
		existingEnv.NEXT_PUBLIC_SUPABASE_URL ||
		"http://127.0.0.1:54321";

	const anonKey =
		statusEnv.ANON_KEY ||
		existingEnv.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
		"";

	if (!anonKey) {
		throw new Error(
			"Could not resolve ANON_KEY from local Supabase. Run `supabase status` and verify the stack is healthy.",
		);
	}

	writeEnvFile({
		NEXT_PUBLIC_SUPABASE_URL: url,
		NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: anonKey,
		SUPABASE_SERVICE_ROLE_KEY:
			statusEnv.SERVICE_ROLE_KEY || existingEnv.SUPABASE_SERVICE_ROLE_KEY || "",
	});

	process.stdout.write(
		`Wrote ${path.basename(ENV_PATH)} with local Supabase keys.\n`,
	);
	if (shouldReset) {
		process.stdout.write("Seed data is loaded. You can now run: pnpm dev\n");
	}
}

try {
	main();
} catch (error) {
	const message = error instanceof Error ? error.message : String(error);
	process.stderr.write(`${message}\n`);
	process.exit(1);
}